[package]
name = "ruby_parser"
version = "0.1.0"
authors = ["take_cheeze <takechi101010@gmail.com>"]

[dependencies]
string_cache = "0.6"
combine = '2.5.1'
ascii = { version = "0.8", default-features = false }
